# Generated by Django 4.2.6 on 2026-02-04 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauzoYote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100000, null=True, verbose_name='Namba Ya Bidhaa')),
                ('JinaLaBidhaa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina La Bidhaa')),
                ('ShopName', models.CharField(blank=True, max_length=500, null=True, verbose_name='Duka Lilipouzwa')),
                ('Category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Category')),
                ('HelaUliyopokea', models.IntegerField(blank=True, default=0, null=True, verbose_name='Hela Uliyopokea')),
                ('KiasiChaBidhaaKilichotoka', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Bidhaa Kilichotoka')),
                ('ImeuzwaNa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Imeuzwa Na ?')),
                ('Created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mauzo Yote',
            },
        ),
        migrations.RemoveField(
            model_name='manunuziyote',
            name='HelaUliyopokea',
        ),
        migrations.RemoveField(
            model_name='manunuziyote',
            name='ImeuzwaNa',
        ),
        migrations.RemoveField(
            model_name='manunuziyote',
            name='KiasiChaBidhaaKilichotoka',
        ),
        migrations.AddField(
            model_name='manunuziyote',
            name='HelaUliyotoa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Hela Uliyotoa'),
        ),
        migrations.AddField(
            model_name='manunuziyote',
            name='ImenunuliwaNa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imenunuliwa Na ?'),
        ),
        migrations.AddField(
            model_name='manunuziyote',
            name='KiasiChaBidhaaUlichonunua',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Cha Bidhaa Ulichonunua'),
        ),
        migrations.AlterField(
            model_name='manunuziyote',
            name='JinaLaBidhaa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina La Bidhaa Uliyonunua'),
        ),
        migrations.AlterField(
            model_name='manunuziyote',
            name='ShopName',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Duka lililopokea Bidhaa'),
        ),
    ]
