# Generated by Django 4.2.6 on 2026-02-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0002_mauzoyote_remove_manunuziyote_helauliyopokea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ShopName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.madukayote', verbose_name='Duka'),
        ),
    ]
